FROM arm32v7/node:lts-slim

WORKDIR /app/

# Install Package.json dependendencies
COPY package.json .
RUN npm install -g npm@latest \
    && npm -v \
    && npm install

# Copy Source Code
COPY . .

USER node

CMD ["npm", "run", "start"]

