apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-worker-input
  namespace: default
spec:
  type: bindings.rabbitmq
  metadata:
  - name: host
    value: amqp://rabbitmq.default.svc.cluster.local:5672
  - name: queueName
    value: rabbitmq-worker-input