apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString # Required
    value: "Endpoint=sb://sbnc4731918.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=gEetjldYW0GE4szYA6VUotw6wghdRYLMjVQAq3hosUs="
  - name: ttlInSeconds
    value: 60
  - name: maxActiveMessages
    value: 1