apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-queue
  namespace: default
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString # Required
    value: "YOUR_CONNECTION_STRING"
  - name: queueName
    value: worker-items
  - name: ttlInSeconds
    value: 60
